### ISSUE TITLE
pubsub debian packages

### ISSUE THREAD

**Issue by stuaxo** [nehz/avalon#1]
Hi,
   This isn't about avalon, but about pubsub  https://bitbucket.org/nehz/pubsub   - but the issue tracker there is not enabled.

Is there any chance of debian packages for pubsub (?) - it's been super useful inside my own app Shoebot.

S

**Comment by nehz** [comment]
It should be available on pypi (https://pypi.python.org/pypi/pubsub)
Glad this little package I made years ago is being used :)

**Comment by stuaxo** [comment]
It is on pypi.   I'd like to make a deb package of Shoebot, that uses this (so hence need a deb of pubsub).  

I was able to generate a package using stdeb, I can go ahead and try and get that submitted, if you're good with it.

pubsub has something I find really difficult in my own code - simplicity :)

would it be alright to enable the issue tracker on bitbucket, or just move it to github ?

BTW - getting this building on python 3 (I haven't tested it though) - is a two line change - changing "0L" to "0"

```
diff -r 1d23c5b0bc00 pubsub.py
--- a/pubsub.py Thu Oct 25 15:51:03 2012 +0800
+++ b/pubsub.py Sat Oct 10 14:11:22 2015 +0800
@@ -95,12 +95,12 @@
     if PUBLISH_ID:
         count_lock.acquire()
         if channel not in count:
-            count[channel] = 0L
+            count[channel] = 0
         else:
             count[channel] = (count[channel] + 1) % MAX_ID
         count_lock.release()
     else:
-        count[channel] = 0L
+        count[channel] = 0

     # ID of current message
     _id = count[channel]
```

here is a cmd that uses stdeb to generate packages (py3 bit commented out as needs patch)
https://gist.github.com/stuaxo/9ea405006f389564a363

**Comment by nehz** [comment]
Sure go ahead; I am not familiar with the debian ecosystem.
Made a repo on github: https://github.com/nehz/pubsub
Updated to py3.

**Comment by stuaxo** [comment]
Cheers - will move discussion to that repo :)
